package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"context"

	"github.com/amitpoitrix/go-graphql/internal/graph/model"
)

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, input model.NewBook) (*model.Book, error) {
	book, err := r.bookService.CreateBook(input.Title, input.Author, input.Year)
	if err != nil {
		return nil, err
	}

	return &model.Book{
		ID:     book.ID,
		Title:  book.Title,
		Author: book.Author,
		Year:   book.Year,
	}, nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	books, err := r.bookService.GetAllBooks()
	if err != nil {
		return nil, err
	}

	result := make([]*model.Book, len(books))
	for i, book := range books {
		result[i] = &model.Book{
			ID:     book.ID,
			Title:  book.Title,
			Author: book.Author,
			Year:   book.Year,
		}
	}
	return result, nil
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, id string) (*model.Book, error) {
	book, err := r.bookService.GetBookByID(id)
	if err != nil {
		return nil, err
	}

	return &model.Book{
		ID:     book.ID,
		Title:  book.Title,
		Author: book.Author,
		Year:   book.Year,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
